### ISSUE TITLE
Thunderbird 78.6.1 does not connect with google calendar

### ISSUE THREAD

**Issue by johnk860** [kewisch/gdata-provider#153]
### Describe the problem and steps to reproduce it:
Went to Lightning Calendar on Thunderbird 78.6.1.  Calendar was blank.  Checked Add-ons, Lightning no longer appears - it apparently is now included in the T-Bird download.  Provider for Google Calendar is still installed V78.0.1 (11/04/2020) and indicates up to date.  Lightning add on indicates "no update compatible with this version" of T-Bird.

### I first delected T-Bird 78.6.1, restarted my PC and reinstalled 78.6.1.  Calendar still blank.  Restarted again, no change
I then delected 78.6.1, restarted and installed T-Bird 78.6.0 and the calendar resumed operation.  
Lightning is still not in "add-ons" supporting that it is in the T-bird main file and confirming that the update to T-Bird severed contact with Provider.

**Comment by moontime2021** [comment]
Had the same problem for a few days. Installed 78.7.0 just now and seems ok

**Comment by cabal95** [comment]
I missed a few updates so I can't confirm/deny the 78.6.1 issue.

But *can* also confirm that 78.7.0 is working.

@johnk860 Just to note, every version of Thunderbird I have used has an annoying problem (can't say if it's the plugin or Thunderbird itself). When Thunderbird is first launched the calendar will be blank until you toggle the visibility off and back on for your `username@gmail.com` calendar. Just in case that is the problem you are seeing. It's a bit annoying, but since I only every quit Thunderbird on restart, which is maybe once a week, it hasn't been that much of a bother to me.

**Comment by johnk860** [comment]
An update:  Yup.  Needed to "unsee" and then "resee" the various calendars and all was there again.  Problem: insufficient instruction and/or insufficient attention to reacquiring data after the update.  I found this answer after my wife said her calendar wasn't working (as bad as I am, I'm the go-to computer guy in the house) and, at the same time, I got a response about reinitializing the calendars as a possible answer.
Complicating all this happiness is that, while typing this reply I opened Thunderbird Calendar and everything was blank again!?!  I "unsaw" and "resaw" my 8 calendars and they're all back in view.  Now I have to worry about whether this is a recurring issue.
