### ISSUE TITLE
403 forbidden dismissing event notification (Bugzilla Bug 1150571)

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#3]
# [Bugzilla Bug 1150571](https://bugzilla.mozilla.org/show_bug.cgi?id=1150571)
Date: 2015-04-02T18:21:45+02:00
From: @dblohm7
Assigned To:   nobody

Depends on:  [bug 1101175](https://bugzilla.mozilla.org/show_bug.cgi?id=1101175)
Blocker for:  [bug 1314185](https://bugzilla.mozilla.org/show_bug.cgi?id=1314185)
Last updated: 2019-09-11T13:39:25+02:00

**Comment by kewisch** [comment]
Yep, I need to rewrite this to check the differences between `oldItem` and `newItem` in a performant way, and then send only what really changed. Not particularly complicated, but needs to be done :)

**Comment by frittentheke** [comment]
@kewisch thank you very very much for looking into this. This really not just annoying, but makes Google Calendar borderline unuable in Lightning when you have lots of recurring events (think "Scrum dailies" ... I have this problem absolutely solidly. 

Is there a hotfix or proposed change that I could test in my environment?

**Comment by kewisch** [comment]
I don't have any code written for this. Would you or someone on your team be interested in looking into a fix?

**Comment by csnook** [comment]
This doesn't happen at all if I mark the calendar with the offending events read-only. Does that also break notifications?

It also doesn't happen for instances of the notification that happen after import, as far as I can tell.

It may be easier to avoid ever hitting the codepath than to deal with screwy PATCH semantics.

**Comment by TheCrazyT** [comment]
The official documentation about PATCH does not mention that values that keep the same won't be overwritten ,guess that was just a wrong assumption.
But now it is a problem because an access validation fails for some fields.
Dismissing should really just send a PATCH with "x-moz-lastack".

**Comment by csnook** [comment]
I found a simple (but racy) workaround: remove the calendar, then re-add it and mark it read-only immediately, before it finishes importing any of the offending events. Wait until it has finished importing all the events, sync again, close and restart Thunderbird to make absolutely sure it's done importing, and then mark it writable. The problem hasn't come back yet, though I don't understand it well enough to know if that can be relied upon.

It took a while to get the calendar properties to load while the import was running, but fortunately the offenders are more than a thousand events deep in my calendar, so I had time.

**Comment by solomonsunder** [comment]
I updated to Thunderbird 68.2.1 and installed the equivalent plugin and have the same problem ie 403 forbidden when I do a dismiss. I updated from Thunderbird 68.0 and 4.4 plugin ie the default Ubuntu 18.04 versions which also had these problems.

Removing calendar, doing read only mentioned by the last commenter does not work for me.

**Comment by robertjk** [comment]
> I found a simple (but racy) workaround: remove the calendar, then re-add it and mark it read-only immediately, before it finishes importing any of the offending events. Wait until it has finished importing all the events, sync again, close and restart Thunderbird to make absolutely sure it's done importing, and then mark it writable. The problem hasn't come back yet, though I don't understand it well enough to know if that can be relied upon.
> 
> It took a while to get the calendar properties to load while the import was running, but fortunately the offenders are more than a thousand events deep in my calendar, so I had time.

Tried doing exactly that twice, but it doesn't fix anything for me either.

**Comment by boschi** [comment]
Also have the same issue.
The only workaround that alleviates the problem for me is opening the calendar in Google's web UI, editing the offending events by deleting the reminders, saving, re-sync'ing the calendar in Thunderbird, then back at the Google Calendar's web UI, re-enabling the reminders (only for the recurring events)

**Comment by d3ngar** [comment]
Yeah, I'm not sure what's going on here. This has been an annoying bug for years now (5-years actually). And since I've been moving to Thunderbird more and more, especially now that we are quarantined, it's getting really frustrating.

If I can make a suggestion: add the event to a "black-list" that will never ever crop up again in Thunderbird. Essentially exclude it from the calendar completely.

I will now try to do what @robertjk  suggested and report back if this works. It's the third time that I remove the calendar.

**Comment by nmoreaud** [comment]
Hello,
Did you find other workarounds that "hide missed reminders" ?
I have alerts that pop every 10 minutes for the same events, it prevents me from concentrating...

**Comment by ryzokuken** [comment]
Any fix yet?

**Comment by ptous** [comment]
As potentially useful information, you get this same error (on the exact same calendar events) whether you use the gdata provider or access Google Calendar "directly" using CalDAV.

That suggests this is not really a gdata provider issue, though it may be something you could handle more gracefully in the provider.

(I don't really get why the calendar entry _needs_ to be updated for notification dismissals, but I'm not really up on how standard calendar interactions work.)

**Comment by ryzokuken** [comment]
Yeah, I decided to just make the Google Calendar read-only which works really well for me.

**Comment by kewisch** [comment]
fwiw, I'm rewriting parts of the Provider to be future proof for Thunderbird 90, and as part of that I intend to change how event modifications are changed (using PATCH instead). Doing so would fix most issues related to the 403 with invitations.

**Comment by pszalanski** [comment]
Is there any progress on the fix? I am still experiencing this issue.

**Comment by jaysonlarose** [comment]
I seem to be experiencing this issue as well... Thunderbird 78.11.0 (64-bit), Provider for Google Calendar 78.0.1.

I'm not above petty bribery to get this fixed. If there's an update to Provider for Google Calendar that makes my event dismissing problem go away within a month, I'll feel compelled to hit the "♥ Contribute" button on the Addon Details page, edit the "10eur" part of the url to "50eur", and hit the send button.

**Comment by kewisch** [comment]
This should be fixed on the `main` branch, therefore I'm closing the issue. It will still be a bit until I can release, see #224. I very much appreciate your support <3

**Comment by Joaobranquinho** [comment]
@kewisch is there a release planned to fix this?

**Comment by peci1** [comment]
> This should be fixed on the `main` branch, therefore I'm closing the issue.

I'm interested in knowing how exactly have you fixed this issue. Until #224 is merged, I was searching for a manual solution using either Google API Explorer or a script. However, sending PATCH with the simplest possible content fails with the 403 Forbidden for events where I'm not an organizer:

```
{
  "extendedProperties": {
    "private": {
      "X-MOZ-LASTACK": "2022-07-02T00:20:57Z",
      "X-MOZ-SNOOZE-TIME": null
    }
  }
}
```

Have you actually tried the fix on events where you're not an organizer?

**Comment by exteon** [comment]
So would there be any chance of backporting the fix to patch the current release? It's such an usability showstopper...

**Comment by glide007** [comment]
is there a way I can take beta or unreleased version?

**Comment by karltach** [comment]
Every zoom meeting invitation I get does this. It is so irritating, if possible I would like a workaround option to block reminders based on the zoom invitation text that is in the description.

**Comment by eivindt** [comment]
I see yet another mention of this bug in #542, and while I'm sure the eventual release from the main branch will fix this, here's my simple patch that fixes this for me (any maybe me only) on the legacy branch:

```patch
diff --git a/src/legacy/modules/gdataCalendar.jsm b/src/legacy/modules/gdataCalendar.jsm
index c0b201d..af7a895 100644
--- a/src/legacy/modules/gdataCalendar.jsm
+++ b/src/legacy/modules/gdataCalendar.jsm
@@ -493,7 +493,8 @@ class calGoogleCalendar extends cal.provider.BaseClass {
         // Updating invitations often causes a forbidden error because
         // some parts are not writable. Using PATCH ignores anything
         // that isn't allowed.
-        if (cal.itip.isInvitation(aNewItem)) {
+        if (cal.itip.isInvitation(aNewItem) || aNewItem.organizer.id != "mailto:" + this.mCalendarName) {
+          console.log(`Changing request type to PATCH, since organizer ${aNewItem.organizer.id} != mailto:${this.mCalendarName}`)
           request.type = request.PATCH;
         }
 
```

I.e. if the organizer of the event is not the current user, change request type to PATCH.  I've been running with this patch for a couple of weeks without issues.

**Comment by Joaobranquinho** [comment]
@eivindt Can you create a PR for it? Would be greatly appreciated :)

**Comment by eivindt** [comment]
I'll try to do that tomorrow unless someone explains why my change is a stupid idea. ;)

**Comment by peci1** [comment]
@eivindt  This still doesn't work for me.

I see the `Changing request type to PATCH` in the log, but then the error again:

```
[calGoogleCalendar] Modifying item *** failed:2147500037: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
```

**Comment by eivindt** [comment]
Yes, unfortunately, still not perfect.  I have no idea why yours is failing @peci1 your error message seems to indicate no access to the calendar at all, which isn't the type of error my small patch was trying to fix.
I've also got a stuck reminder now, which seems to be caused by the event never being refreshed.  I don't know if my patch somehow is causing this or if it is something else.

**Comment by peci1** [comment]
I'm not sure if it's relevant here, but I have an open support case with Google regarding the calendar API. This is an excerpt:

this error was probably in misunderstanding of the API docs. I had account A and an event in it. Then I shared A's calendar to B as readonly and wanted to call PATCH changing extendedProperties/private in the B account.

The docs on extended properties say:

> Shared properties are visible and editable by all attendees of an event, while private properties are set on one attendee's local "copy" of the event. More concretely, private properties are specific to the calendarId and eventId used in the request, while shared properties will be shown regardless of the calendarId used in the request.
I imagined that even user B has a "local" copy of the event, but that would only be true if B were an invited participant of the event. But that was not the case, B had just a readonly share of the calendar. And since private extended properties are unique to a combination of calendarID-eventID, it makes sense that B cannot change the private properties, because calendarID is the same for both A and B.

Maybe it would help to improve wording of this part of docs on https://developers.google.com/calendar/api/guides/extended-properties to also mention that the "local copy" of the event is not made for accounts that share access to the calendar but are not invited.

**Comment by dlech** [comment]
The @eivindt patch from https://github.com/kewisch/gdata-provider/issues/3#issuecomment-1323832877 fixed a couple of undismissable events that kept popping back up every few minutes and was annoying me for days. Did a PR ever get made?

**Comment by eivindt** [comment]
Sorry for the late response.  I never did make a PR for this.  The main reason is that I still have situations where I cannot dismiss event notifications, and digging into these, trying to find the correct resolution has been difficult.

I'll see if I can create a PR for this situation, and create separate issues for the other situations that I see.

**Comment by MoralCode** [comment]
here is my experience in case it helps: I was experiencing the same issue where every time my main google calendar (the one with my email address as its name) would refresh/resync id get an alert with reminders that were entirely from events i had been invited to/attended. dismissing them did nothing and i was able to find this issue by searching for the error messages that appeared in the Tools >Developer tools > error console menu when i clicked to dismiss the individual events.

**My workaround**
After getting annoyed with this, I went on google calendar directly and noticed that i could make edits to only certain parts of the event (most, like the description,  had a yellow background, which i suspect means i cant edit that, which makes sense since i dont own the event). I noticed Google calendar would let me edit/remove the reminders though.

After removing reminders from the affected events (and also unsubscribing/re-adding that calendar in thunderbird), i dont get the annoying reminder popups anymore (i think).

I also suspect (although I dont know this codebase and admittedly havent checked myself) that some of the errors from this extension might be because the extension is assuming that none of the fields are editable in a shared event, when it seems like the reminders one at a minimum is designed to be (and maybe things like color too?)


hope this helps, if only to provide an extra workaround

**Comment by peci1** [comment]
> and also unsubscribing/re-adding that calendar in thunderbird

This doesn't seem necessary. Restarting TB usually helps me.

**Comment by clari7744** [comment]
I'm still having this issue on thunderbird v128.6.0esr-1 rev:609; Provider for Google Calendar v128.0.0; Ubuntu 24.04. Thought I'd bring it up here since this seems to be the actual issue for it?

**Comment by kevgrig** [comment]
Editing the event on calendar.google.com and removing the notification fixes this but I'm just curious if this notifies the organizer in any way? I hope not

**Comment by clari7744** [comment]
@kevgrig it would not; notifications are personal on GCal.
