### ISSUE TITLE
very odd duplicate being sent by gmail when accepting a calendar invite

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#347]
### Discussed in https://github.com/kewisch/gdata-provider/discussions/314

<div type='discussions-op-text'>

<sup>Originally posted by **redstang33** November 11, 2021</sup>
Hi,

I have seen this happen twice now and it's embarassing to me. Here's what happens:
- I get a calendar invite in my (non-google) email.
- I accept the invite in Thunderbird to my google calendar.
- I get a pop-up "Party crashing? You are not on the guest list yet. Respond as:" and I choose the email address the invite was sent to. Note that at this point my private email is indeed on the guest list, however not the gmail account that I accept the invite into.
- The sender receives the confirmation e-mail that I accepted the entry

HOWEVER: At this point EVERYBODY that was invited to the original invite receives a NEW invite from my google-account I used to accept the invite into duplicating the original invite.

This only started to happen with Thunderbird 91.1.2 that got installed with a recent Ubuntu upgrade I'm using. Hence it might very well be related to Thunderbird and not the gdata-provider plug-in.
</div>

**Comment by kewisch** [comment]
Hmm, the telling line may be Calendar GCalendar is unavailable, adding item offline. The event is saved in the cache, and then later replayed. I'm not sure why the replayed item would have an organizer that doesn't trigger the same 400 error, this would be interesting.

One way to reproduce this quicker is to switch Thunderbird into offline mode, and then go online again. The cached items should then be replayed, so you can capture what is sent to the server at that point.

A potential fix may be to change code in the provider that if this type of 400 error is sent, it is registered as a hard failure, instead of the server being offline. I'm also interested in why Thunderbird is deciding to send an email manually though, not quite sure how to debug this yet.

**Comment by rvavrik** [comment]
Hi, it's still happening in TB 91.4.1 on MacOS 12.1

**Comment by redstang33** [comment]
I have used the recent event around the plug-in and the problem with the google authentication as a chance to completely de-install the addon and test the TB native google calendar. I can confirm that this problem DOES NOT occur when not using the provider plug-in.

I then re-installed and this morning I was able to authenticate. It is happening again. So in order to reproduce this please try this setup:

- You receive a calendar invite to an e-mail that is NOT your gmail.com email address.
- You accept the invite into a google calendar.
- You get the "Party crashing" pop-up and you select your primary (non-gmail) email to reply to the invite.
- At this point you can see the calendar invite locally in TB, however if you check on google.com/calendar it is not there.
- You close TB.
- You restart TB. At this point the entry gets synchronized into google and it then appears on google.com/calendar.
- The owner has changed to the owner of the calendar (the gmail.com address) and this new owner sends an invite to all participants of the meeting including the original organizer.

This is how I reproduced it this morning.

**Comment by rvavrik** [comment]
> I can confirm that this problem DOES NOT occur when not using the provider plug-in.

I have experienced the issue multiple times with pure Thunderbird with no addon/plugin/extension installed. This must be definitely a problem of TB. Currently, I have my Google calendar linked as caldav. Unfortunately, I haven't found the related TB bug report yet.

**Comment by redstang33** [comment]
interesting. Can you list the steps to reproduce the problem? I'm happy to file a bug report on it... I wasn't able to reproduce this using the TB native google calendar support as mentioned above.

**Comment by rvavrik** [comment]
MacOS 12.1
TB 91.5.1 (64-bit), no add-ons installed
1 company email account
1 private gmail account with google calendar added using caldav. The calendar is ​associated with my company email address in TB calendar properties.

1) I receive an email with invitation to an event (organized by the sender) to my company account
2) I click Accept button to the event in the email window of the TB
3) The event is immediately visible in the TB calendar (the google caldav) and there is the "This message contains an event that has already been processed." notification in the email.
4) After a while, I receive a new email from my google address to my company account, with the invitation to the same event, but this time the organizer is my google address and this invitation is sent also to all the participants who were invited to the original event, including the original organizer.
5) I'm embarrassed

Thanks a lot for any help or suggestions.

**Comment by pglpm** [comment]
Same problem here, TB 91.8.1 (64-bit) on Windows 10.
I have a work-related calendar whose email address is set to my work email address. Whenever I accept an invitation sent to that email, TB changes the organizer to myself and sends an "Updated invitation" to all attendees. Quite embarrassing.

Any solutions yet?

**Comment by pkiff** [comment]
Windows 11
TB 102.6.0 (64-bit) 

Same series of steps as @rvavrik in https://github.com/kewisch/gdata-provider/issues/347#issuecomment-1030383393 today, though I did not notice if the event appeared in my TB calendar or not before receiving a new email from Google. 

In my case, when I received a new invite for the same event, but this time from my Gmail account, I looked to see what was going on and the old invitation indicated that the event had been deleted, and nothing was showing in the Lightning calendar at all.

Unfortunately, I have several add-ons, as well as another Gmail account, and several other variables. I will try to do some testing later if I can in order to see if I can reproduce independently. 

Luckily, in my case it was an invitation just for me from one person at a non-Gmail address, so I'm not too embarrassed. :-)

**Comment by lunico65** [comment]
Hi, I experience the same with exactly same setup and situation as described above by [rvavrik].
In the meantime I upgraded to Mac OS 13.1 and it's still the same

**Comment by cnotario** [comment]
Yes, I am experiencing the same issue too. I am using the last version of Thunderbird 102.7.0 and Mac OS Ventura 13.1

**Comment by kewisch** [comment]
Hi folks. If you are experiencing the same issue please provide debug logs as noted in https://github.com/kewisch/gdata-provider/issues/347#issuecomment-1005569089.

**Comment by okko7** [comment]
I have this issue since multiple months now. 
I couldn't figure out to generate a log for debugging. Can someone help me with this?
