### ISSUE TITLE
Sync never complete / missing all events of some calendars after relaunch Thunderbird

### ISSUE THREAD

**Issue by ilNebbioso** [kewisch/gdata-provider#354]
### Describe the problem and steps to reproduce it:

I'm using Windows 10 (full updated) with Thunderbird 91.4.1, Google Provider is 91.0.2.

Once added the plugin and configured, the Sync process starts successfully. 

### What happened?
Some times it seems it completes as well, others no. If I restart TB, the calendar very often is partially complete (some calendars are not sync).
Seems like it cannot complete sync of (quite) crowded calendars.

### What did you expect to happen?
I expect all calendars are synced successfully, and I can add/edit/delete events on them.

Also, into the taskbar often I can read "Syncing of #calendarName, event of", while I expect two numbers as well (in example: "Syncing of #calendarName, event 23 of 153")

### Anything else we should know?
Each test was done with a restart of TB. 
I've got this problem since months, unfortunally.
I also tried to unsubscribe all calendars, unistall Google Provider, reinstall and reconfigure it.
The Gmail account used is also configured (as POP3) for mail dowloading/sending.
The Gmail account has the two factors auth turned on.
I enabled the error console as well, you can find it shown here below.

<a href="https://www.imagevenue.com/ME14AAWJ" target="_blank"><img src="https://cdn-thumbs.imagevenue.com/c4/eb/14/ME14AAWJ_t.jpg" alt="thunderbird.jpg"/></a>

**Comment by kewisch** [comment]
Hmm I am not sure why calendars would be partially synced, if the sync does not complete this should have it retry. What I'd recommend is to unsubscribe from all calendars, then re-subscribe, then let it sit for a long time (e.g. half hour or more). The first sync is slow (in part due to perf issues in Thunderbird), but any subsequent sync should be quick.

As for the missing numbers, I fixed this in 5b73f70d1b2e139786f215b597e097c046ce1f67, but it is only a display issue.

**Comment by arverne73** [comment]
I have quite the same problem I think. One of my Google calendar doesn't synchronise totally ; synchronisation stops always before the end (something like 982/1000). The other calendar of the same account synchronise normally.
On error console I get (screenshot):
![Capture](https://user-images.githubusercontent.com/63741671/152688339-9fcd59bd-1019-4007-87c7-752984fbde34.png)
Is the problem here : "result=item.recurrenceInfo is null" ?
To know : I use TB 91.5 under Ubuntu 21.10 AND GNOME Agenda synchronises all the calendars without problem in the same session.

**Comment by kewisch** [comment]
@ilNebbioso are you seeing the same error as @arverne73 ? This sounds to me like there is some event that has recurring properties, but it is not properly initialized as such. @arverne73 are you able to identify which event exactly causes that error? If so, can you provide the json of the event as received by Thunderbird? This might help identify how the event is parsed.

**Comment by arverne73** [comment]
Hi !
Now I use Ubuntu 22.04 et TB 91.9.1
I have **solved the problem**. Nowadays, **Provider for Google calendar is no more essential** to syn Google calendars with TB ! You need no add-on.
You must simply add a new calendar, choose "On the Network", and on the next dialog, add your Google address as user name and "google.com" as address. And it woks quickly without problem.

**Comment by arverne73** [comment]
And I can add that I never found the event that cause the problem. I tried to remove different events and create them again without result.
If you want to really investigate, I could give you the link to my calendar (nothing "top secret") in a private message…
Thanks.

**Comment by kewisch** [comment]
Alright, closing this issue since you've moved on. If you could share your calendar with me I'd appreciate. My github profile has a few ways to get in touch with me (twitter/email).
