### ISSUE TITLE
Authentication asked every time Thunderbird is started

### ISSUE THREAD

**Issue by PauloGDPeixoto** [kewisch/gdata-provider#36]
Linux
Thunderbird 68.2.1
Provider for Google Calendar 68.2.1

Every time I start thunderbird, with Lightning enabled, I get multiple authentication requests (pertaining to each of my google calendars, I suppose).

**Comment by stm9x9** [comment]
same problem, this was the solution to me: https://github.com/kewisch/gdata-provider/issues/28

**Comment by jirka1297** [comment]
same problem

**Comment by PauloGDPeixoto** [comment]
> same problem, this was the solution to me: #28

I already have general.useragent.compatMode.firefox set to true, I wasn't able to login in thunderbird without setting it. But for some reason, it seems not to have propagated to the add-ons, as the login window seems not to be the firefox compatMode window.

**Comment by PauloGDPeixoto** [comment]
Something I noticed just now, as I removed all the google calendars and tried to re-add them:
![image](https://user-images.githubusercontent.com/20384915/69974229-be0cd100-151c-11ea-9901-da85741a200e.png)

**Comment by aseret-msta** [comment]
same problem too 
Thunderbird 68.2.1
Provider for Google Calendar 68.2.1
Ubuntu 18.04
A problem was on TB previous version too.
I have 10 calendars so I must write username and password ten times after every TB restart :-(

**Comment by ghandmann** [comment]
I can confirm this problem on my machine too. Also setting `general.useragent.compatMode.firefox = true` is not fixing the issue.

Thunderbird 68.2.1 (64-Bit)
Lightning 68.2.1
Provider for Google Calendar 68.2.1
Ubuntu 18.04.

**Comment by PauloGDPeixoto** [comment]
Issue apparently went away after upgrading Ubuntu 18.04 to 19.10.

**Comment by nicolaschiret** [comment]
I confirm this problem too. On Windows 10, Tb 68.3.1, Provider Google Calendar 68.2.1.
I have to enter credentials at every Tb start.

This plugin seems to not be maintained??

**Comment by stevebakes** [comment]
Same issue - Ubuntu 19.10, TB 68.2.2, Lightning 68.2.2, Provider 68.2.1
Issue started after recent update for TB. Was fine after Ubuntu 19.04 to 19.10 upgrade, with previous TB version, then stopped after that TB upgrade. (I think there has been another minor TB release since, but that has not changed anything).
Turned on Firefox useragent compat mode - no effect
Uninstalled provider, removed all calendar passwords/tokens, restarted TB several times, re-added provider - no effect. Still asks for passwords every time.

What information can I provide for you to help fix this issue?

**Comment by ghandmann** [comment]
The problem went away after removing all Google-Calenders and re-adding them.

**Comment by nicolaschiret** [comment]
Yes, I already tried to remove calendars but authentification is needed at every thunderbird start.
I update to TB 68.4.2...not resolved.

**Comment by ghandmann** [comment]
@kewisch i really don't want to offend you by highlighting you here, but did you even recognize this issue?

**Comment by boldsoon** [comment]
TB 68.7.0 fresh install with Provider 68.2.1 keeps doing this verification.

**Comment by stevebakes** [comment]
Seems to be working for me now. Removed calendars, then went to stored passwords and removed ALL oauth tokens for calendars. Restart TB, then re-add calendars. It asked once for my password and has not re-asked since. (3 days ago). So relieved after months of having to enter passwords every time. TB 68.7.0 / Provider 68.2.1.

**Comment by boyanpenkov** [comment]
Same here.  @stevebakes does yours still work, or are you also observing what @ghandmann saw where it comes in again?

**Comment by stevebakes** [comment]
@boyanpenkov Mine is still working, however it has only been 5 days. It might be another week or so before I can relax when I open TB.

**Comment by boyanpenkov** [comment]
Good to hear -- FWIW, I "solved" my problem by using the CALDAV interface and not using Provider; not sure if this is temporary...

**Comment by jngrb** [comment]
> Something I noticed just now, as I removed all the google calendars and tried to re-add them:
> ![image](https://user-images.githubusercontent.com/20384915/69974229-be0cd100-151c-11ea-9901-da85741a200e.png)
> Seems like the add-on is not picking up the existing session.

I can confirm this problem (I was stuck with it for one day after upgrading to Focal Fossa). I made the same experience as Paulo: when I hit Next on this page of the dialog without entering any account, I get the login dialog and can add my calendars for syncing. But I have to relogin every time I restart Thunderbird.

When I add my account name into the empty input box and only then hit Next, everything is OK and my login information is persisted.

As I cannot hit Next, when I am back to this dialog and I already have my real account, I think the "fix" is to prevent "Next" for the empty dialog. One should always have to enter the account name there.

![Calendar_add_account](https://user-images.githubusercontent.com/7009550/80871332-3d5d2700-8cac-11ea-9cd9-9cdf945d05c7.png)
![Calendar_add_account2](https://user-images.githubusercontent.com/7009550/80871336-3fbf8100-8cac-11ea-86ac-2478c2568424.png)

**Comment by B00ze64** [comment]
Good day Phillip.

TB 60.9.1 (x64)
Lightning 6.2.9.1
Provider for Google Calendar 4.4.2

I updated from TB38 to TB60 this week and discovered the old "OAuth on every TB Launch" problem is back with Lightning. You worked on that a long time ago (I still have some debug versions of Lightning 2.6) unfortunately it looks like the issue has returned. This started happening around TB52 I think (I was updating from version to version and not fully testing until I hit TB60). Definitively happening with TB60.

I was using Caldav to access my Google calendars, and looked at the Lightning logs in the console, but you do not log much for Caldav and nothing seemed amiss, except that every time I ran TB and did the OAuth, a new token was added to the credentials manager.

So I decided to try the provider. Same issue, but this time you log more into the console.
I am attaching 2 runs of TB back to back. The thing that has me puzzled is this ->
```
Lightning:[calGoogleSession] Token expired 1600318005 seconds ago, resetting  gdataSession.jsm:341
Lightning:[calGoogleCalendar] Logging in session REDACTED@gmail.com  gdataSession.jsm:237
Lightning:[calGoogleCalendar] No access token for REDACTED@gmail.com, refreshing token  gdataSession.jsm:302
```
Every time Lightning Launches, the token is expired since ~50 years, not sure this is normal. Also noticed that the provider does not store the token in the credentials manager (that might be normal).

Anyway, I would greatly appreciate a fix for TB60, as I will not be ready to move onto a newer TB for a long time. For one, I use a Full Theme and the future for those is uncertain, and I am willing to wait until MailExtensions have matured - I've already lost a few extensions by moving-up to TB60...

[Provider-1.txt](https://github.com/kewisch/gdata-provider/files/5243150/Provider-1.txt)
[Provider-2.txt](https://github.com/kewisch/gdata-provider/files/5243149/Provider-2.txt)

Thank you.
Best Regards.

**Comment by B00ze64** [comment]
Good day all.

I figured what the issue was, at least for my own setup -> I had "signon.rememberSignons" set to FALSE. On Firefox this controls the auto-complete of passwords in forms, but in TB this controls the password manager globally. I discovered the issue when I had to enter a password for an email account and the "Remember" checkbox was missing.

Thank you.
Best Regards,

**Comment by kewisch** [comment]
Thanks for the debugging here! #161 should cover the remaining part of this issue
