### ISSUE TITLE
Option "Force use of plain text in event descriptions" does not work

### ISSUE THREAD

**Issue by L-UL** [kewisch/gdata-provider#412]
### Describe the problem and steps to reproduce it:

I need to activate the option: "Force use of plain text in event descriptions" to solve sync issues between Lightning and Google Calendar, and between Google Calendar and an external sms marketing service, whose platform does not get on well with HTML language,

### What happened?

When I put the tick next to "Force use of plain text in event descriptions" to activate this option, and then I close the tab/window, the tick disappears every time.
Moreover the sync between Lightning and Google Calendar continues to not work properly and the event that is generated on Google Calendar still contains html signs. like: "< body > \ n < div >"

### What did you expect to happen?

I expected Google Calendar to generate an event with full plain text,

### Anything else we should know?

Thunderbird version: 91.7.0 (32 bit)
Provider per Google Calendar version: 91.0.4
![Force use of plain text_screenshot](https://user-images.githubusercontent.com/101660529/158434589-c11d30ac-b90e-4306-97bf-dc3ec1ca4dad.PNG)

**Comment by kewisch** [comment]
I've added a fix that persists the option correctly, if you could give that a try after the release I'd appreciate. The option does not fully force plain text, events that fit certain criteria will be parsed as HTML when they come in. The option will use plain text when saving an event.

There is no clean solution at the moment with HTML since the server uses one field for both plain text and html representations.

If you could file a new issue after the release in case this doesn't work as expected I'll take another look.
