### ISSUE TITLE
Clattering events with HTML tags on iPhone Calendar app

### ISSUE THREAD

**Issue by sergtk** [kewisch/gdata-provider#432]
### Describe the problem and steps to reproduce it:

* Create event with links via gdata-provider plugin in Thunderbird so the event with link formatted and added to calendar.
The issue can be also reproduced when editting existing event with links.
New lines may also result in bug reproducing

* Connect this calendar in the build in Calendar app on iPhone.

### What happened?

* Cluttering with many HTML tags when open event on Calendar app on iPhone.

### What did you expect to happen?

* See the same text on iPhone and in Thunderbird.

### Anything else we should know?

* As a workaround the Google calendar clients may be used to copy and paste text.

* This behavior is relatively new, probably several month old. Before this gdata-provider worked fine

**Comment by kewisch** [comment]
I added an option to force plain text, you could give that a try. Unfortunately the HTML situation is messy, since Google Calendar users the same field for both HTML and non-HTML descriptions, and it is not easy to detect which it is. Then, Thunderbird added a "feature" to allow HTML editing, which I needed to implement to be compatible.

I'm going to have to close this as there is not much more I can do.

**Comment by sergtk** [comment]
Thanks, I  will try.
Just I want to add that there is no conflicts between Google applications (mobile and web version) and iPhone/Mac applications. They manage this situation in some way.
But I got this issue with Thunderbird only.
Thanks

**Comment by sergtk** [comment]
Do you plan to publish new release with this feature? Thanks

**Comment by kewisch** [comment]
The feature is already there, though admittedly there is an issue with persisting the option which I will be releasing a fix for shortly.
