### ISSUE TITLE
CalDav vs Provider for Google Calendar(gdata-provider)

### ISSUE THREAD

**Issue by robertour** [kewisch/gdata-provider#537]
I am really confused about what this extension is for. I got to it because it supposed to be the way in which read and write operations are allowed to Google Calendar from Thunderbird. I tried it and it didn't work but I believe it is because something is currently broken and being fixed.

In any case, I managed by just using the default Thunderbird functionality and CalDav. The syncing is working so far without issues and without the extension.

What am I missing?

**Comment by kewisch** [comment]
I don't have a full overview on what works better in each. Google's CalDAV support was tacked on to their backend and it feels like it has been left alone since. For many cases it will "just work", but there are some cases where the Provider works better. I have some customizations for the event dialog that won't be availabl in CalDAV. Also, the Provider supports tasks, which CalDAV does not. Hope this helps?
