### ISSUE TITLE
Dismissing reminder for my event with attendees deletes the attendees

### ISSUE THREAD

**Issue by peci1** [kewisch/gdata-provider#575]
I know this has already been discussed: #320, #184, #156, #138. All of these issues are marked as fixed. However, fixing them on the main branch is not enough - there are thousands of people running on stable versions who do not yet have these fixes and they are suffering harsh data loss and embarassing situations.

I don't say you have to backport the fix to stable versions, @kewisch , but what you should really do is **implementing a popup that would inform the user that this kind of data loss is about to happen** when he snoozes the reminder (or edits the event, or whatever). Now I know there is the option to support working with attendees. But as it is off by default and there was no announcement in TB that I should enable it, I was in a situation as every normal TB user - having this off, suffering data loss.

Just a side question: Does mozilla or the related foundation(s) support development of this addon, or is it purely volunteer-developed?

**Comment by kewisch** [comment]
This add-on is purely volunteer-developed, which means me and some occasional pull requests. Donations welcome https://fosstodon.org/@kewisch/110672484200522920 :-)

Do you have the event scheduling and attendee preferences enabled? I'm a bit reluctant to enable them by default because I've seen past cases where folks re-invited their whole company to a new event when they interacted with it. I don't have a reliable way to always do the right thing at the moment, or lets say I don't know what edge cases might show up.
