### ISSUE TITLE
Tasks not automatically syncing on T-Bird open

### ISSUE THREAD

**Issue by hfball** [kewisch/gdata-provider#645]
### Describe the problem and steps to reproduce it:
Calendar syncs on open. Tasks has failed to sync on open for the past few months on my machine.

### What happened?
Tasks did not sync on launch.

### What did you expect to happen?
They should sync just like the calendar does on launch.

### Anything else we should know?
Windows 11, 22H2 22621.2134, Thunderbird 102.14.0

**Comment by chilidad** [comment]
Similar issue as well as tasks not synchronising (manually or auto) unless I close out of TB and reopen. These issues seem to have been present since 2 releases ago. However, just temporarily disabling/re-enabling Google Provider did fix the problem. This solution came from same as previous poster's link https://github.com/kewisch/gdata-provider/discussions/497, worked for me!

**Comment by kewisch** [comment]
With debug logging enabled, do you get messages like  `[calGoogleCalendar] Skipping refresh since user is idle` while you are not in fact idle?

**Comment by hfball** [comment]
I do not understand why, but I am no longer having this issue. If chilidad reports the same, then I think you can close it out.

**Comment by kewisch** [comment]
Thanks for letting me know. Please report a new issue if this is still the case for anyone else.
