### ISSUE TITLE
Calendars Fail to Enable/Sync After Upgrade to 115.3.0

### ISSUE THREAD

**Issue by jmangum** [kewisch/gdata-provider#768]
### Describe the problem and steps to reproduce it:

After upgrade to gdatda-provider 115.3.0 with TB 115.11.0 my subscribed google calendars, which I have used with gdata-provider for many years, fail to enable/sync.  When viewing my calendars in TB, my two google calendars show status "ENABLE".  When I click ENABLE the calendar briefly displays, but then switches back to ENABLE and disappears.

### What happened?

Calendars no longer display, enable, or sync.

### Anything else we should know?

Looking at the console, I see the folliwng when I try to enable a calendar:
```
Calendar: CalDAV: send (PROPFIND https://apidata.googleusercontent.com/caldav/v2/jgmangum%40gmail.com/events/): <?xml version="1.0" encoding="UTF-8"?>
<D:propfind xmlns:D='DAV:' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:CS='http://calendarserver.org/ns/'><D:prop><D:resourcetype/><D:owner/><D:current-user-principal/><D:current-user-privilege-set/><D:supported-report-set/><C:supported-calendar-component-set/><CS:getctag/></D:prop></D:propfind> [CalDavRequest.jsm:126](resource:///modules/caldav/CalDavRequest.jsm)
Calendar: CalDAV: recv: <?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>notFound</code>
  <internalReason>Not Found</internalReason>
 </error>
</errors>
[CalDavRequest.jsm:145](resource:///modules/caldav/CalDavRequest.jsm)
[calCachedCalendar] replay action failed: <unknown>, uri=https://apidata.googleusercontent.com/caldav/v2/jgmangum%40gmail.com/events/, result=2147500037, operation=[xpconnect wrapped calIOperation]

​```

**Comment by kewisch** [comment]
It appears you are using CalDAV, and not the Provider for Google Calendar. Make sure to select Google Calendar when subscribing to the calendar.

**Comment by kewisch** [comment]
No worries! The `googleapi://` calendars are via the Provider for Google Calendar. For invitations to work, you need to enable a few settings in the add-on preferences and should then re-subscribe to the calendars. Note however due to the Thunderbird code invitations are a bit finicky and might cause some issues. I'd recommend keeping invitations notifications off for a bit while you test things.

For invitations, I'd generally recommend to use the "Automatically add invitations to my calendar" feature in the Google Calendar web settings, and not interact with invitation emails through Thunderbird.

Feel free to file a new issue if you run into any other bugs!
