### ISSUE TITLE
Google won't let me sign in

### ISSUE THREAD

**Issue by leefel** [kewisch/gdata-provider#80]
***Sorry if this is answered elsewhere, but I couldn't find anything addressing it.***

I'm having problems syncing with my Google calendar. A popup asks for my email address, which I enter and then click NEXT. The next popup then asks for an email address or phone number, but neither of these accomplishes anything useful.  After a couple of tries, Google eventually sends me to a help page, which is no help.

I know my Google credentials are right, because I can log on to the Google calendar on my browser.

Here's the log: (log removed for private data)

**Comment by liamkirsh** [comment]
Do you have cookies enabled? When setting up my calendar, I was prompted to repeatedly enter in my Google email address. Enabling cookies in Thunderbird settings fixed the problem.

**Comment by kewisch** [comment]
Yes, please try enabling cookies, and see https://github.com/kewisch/gdata-provider/wiki/FAQ#enabling-debugging for details on providing the right logs. I'm closing this issue for now since I've seen a few other related issues that might have more information, but I'm keeping an eye out on this case.
