### ISSUE TITLE
Calendars choice is empty

### ISSUE THREAD

**Issue by Bailed** [kewisch/gdata-provider#87]
Hi 

Using Thunderbird 68.1.X and GData 68.2.1.

Plugin installation is ok
Reboot Thunderbird is ok
New calendar option "Google Calendar" is ok
Third-party authorization screen is ok and allowed
But no calendar is available in the choice screen. It's leaving it empty and blank.

BR

**Comment by theresetmaster** [comment]
Hi 

I have the same problem - or all most the same

It works for my personal calendar, but not when I try to add my organisation gmail. 

BR

**Comment by BerndErnst** [comment]
Same problem here

**Comment by cavemanr** [comment]
I've the same problem with 2 of my 3 Company Gmail Accounts.

**Comment by kewisch** [comment]
#88 notes issues with 2FA on company calendars. Can you comment there if you have more info? Otherwise, can you check out the [FAQ](https://github.com/kewisch/gdata-provider/wiki/FAQ) and provide debugging information? I'm closing this as duplicate for now, but if this appears on a personal calendar and there are hints in debugging I'd appreciate a comment.
